import Joi from "joi";

export const entrepriseSaveSchema = Joi.object({
  nom_entreprise: Joi.string().allow(""),
  lieuSiege: Joi.string().allow(""),
  contact: Joi.string().allow(""),
  email: Joi.string().allow(""),
  date: Joi.string().allow(""),
  groupe: Joi.string().allow(""),
  ville: Joi.string().allow(""),
  commune: Joi.string().allow(""),
  group1: Joi.string().allow(""),
  group2: Joi.string().allow(""),
  group3: Joi.string().allow(""),
  name_1: Joi.string().allow(""),
  name_2: Joi.string().allow(""),
  name_3: Joi.string().allow(""),
  name_4: Joi.string().allow(""),
  name_5: Joi.string().allow(""),
  group5: Joi.string().allow(""),
  activites: Joi.string().allow(""),
  employeTotal: Joi.string().allow(""),
  employeFemme: Joi.string().allow(""),
  employeHomme: Joi.string().allow(""),
  nomPrenom: Joi.string().allow(""),
  groupe1: Joi.string().allow(""),
  groupe2: Joi.string().allow(""),
  email_2: Joi.string().allow(""),
  telephone: Joi.string().allow(""),
  whatsapp: Joi.string().allow(""),
  compte_fb: Joi.string().allow(""),
  fonctions: Joi.string().allow(""),
  groupes1: Joi.string().allow(""),
  raison: Joi.string().allow(""),
  programme_raison: Joi.string().allow(""),
  motivation: Joi.string().allow(""),
  connaissances: Joi.string().allow(""),
  equipement: Joi.string().allow(""),
  groupes2: Joi.string().allow(""),
  groupes3: Joi.string().allow(""),
  comment: Joi.string().allow(""),
  groupes4: Joi.string().allow(""),
  partage: Joi.string().allow(""),
  transformation: Joi.string().allow(""),
  groupes5: Joi.string().allow(""),
});
