-- CreateTable
CREATE TABLE `Entreprise` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `nom_entreprise` VARCHAR(191) NOT NULL,
    `lieuSiege` VARCHAR(191) NOT NULL,
    `contact` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `date` VARCHAR(191) NOT NULL,
    `groupe` VARCHAR(191) NOT NULL,
    `ville` VARCHAR(191) NOT NULL,
    `commune` VARCHAR(191) NOT NULL,
    `group1` VARCHAR(191) NOT NULL,
    `group2` VARCHAR(191) NOT NULL,
    `group3` VARCHAR(191) NOT NULL,
    `name_1` VARCHAR(191) NOT NULL,
    `name_2` VARCHAR(191) NOT NULL,
    `name_3` VARCHAR(191) NOT NULL,
    `name_4` VARCHAR(191) NOT NULL,
    `name_5` VARCHAR(191) NOT NULL,
    `group5` VARCHAR(191) NOT NULL,
    `activites` VARCHAR(191) NOT NULL,
    `employeTotal` VARCHAR(191) NOT NULL,
    `employeFemme` VARCHAR(191) NOT NULL,
    `employeHomme` VARCHAR(191) NOT NULL,
    `nomPrenom` VARCHAR(191) NOT NULL,
    `groupe1` VARCHAR(191) NOT NULL,
    `groupe2` VARCHAR(191) NOT NULL,
    `email_2` VARCHAR(191) NOT NULL,
    `telephone` VARCHAR(191) NOT NULL,
    `whatsapp` VARCHAR(191) NOT NULL,
    `compte_fb` VARCHAR(191) NOT NULL,
    `fonctions` VARCHAR(191) NOT NULL,
    `groupes1` VARCHAR(191) NOT NULL,
    `raison` VARCHAR(191) NOT NULL,
    `programme_raison` VARCHAR(191) NOT NULL,
    `motivation` VARCHAR(191) NOT NULL,
    `connaissances` VARCHAR(191) NOT NULL,
    `equipement` VARCHAR(191) NOT NULL,
    `groupes2` VARCHAR(191) NOT NULL,
    `groupes3` VARCHAR(191) NOT NULL,
    `comment` VARCHAR(191) NOT NULL,
    `groupes4` VARCHAR(191) NOT NULL,
    `partage` VARCHAR(191) NOT NULL,
    `transformation` VARCHAR(191) NOT NULL,
    `groupes5` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
